apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: block-sumo
  namespace: emortalmc

spec:
  fleetName: block-sumo
  policy:
    type: Buffer
    buffer:
      bufferSize: 1
      minReplicas: 1
      maxReplicas: 5
