name: "Build and deploy"

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "emortalmc/actions/java/build@main"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

  deploy:
    needs: "build"
    uses: "emortalmc/argocd-deployments/.github/workflows/sync.yaml@main"
    with:
      deployment-name: "blocksumo"
      version: "${{ github.sha }}"
      values-path: "values/servers/blocksumo.yaml"
